// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomMsgToCompute.proto

package com.mycompany.im.compute.domain;

public final class RoomMsgToCompute {
  private RoomMsgToCompute() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FromConnectorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mycompany.im.compute.domain.FromConnectorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string roomId = 2;</code>
     */
    java.lang.String getRoomId();
    /**
     * <code>string roomId = 2;</code>
     */
    com.google.protobuf.ByteString
        getRoomIdBytes();

    /**
     * <code>string userId = 3;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string nickname = 4;</code>
     */
    java.lang.String getNickname();
    /**
     * <code>string nickname = 4;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>int64 time = 5;</code>
     */
    long getTime();

    /**
     * <code>int32 level = 6;</code>
     */
    int getLevel();

    /**
     * <code>int32 type = 7;</code>
     */
    int getType();

    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */
    int getParamsCount();
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */
    boolean containsParams(
        java.lang.String key);
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getParams();
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParamsMap();
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    java.lang.String getParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    java.lang.String getParamsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.mycompany.im.compute.domain.FromConnectorMessage}
   */
  public  static final class FromConnectorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mycompany.im.compute.domain.FromConnectorMessage)
      FromConnectorMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FromConnectorMessage.newBuilder() to construct.
    private FromConnectorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FromConnectorMessage() {
      messageId_ = "";
      roomId_ = "";
      userId_ = "";
      nickname_ = "";
      time_ = 0L;
      level_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FromConnectorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 40: {

              time_ = input.readInt64();
              break;
            }
            case 48: {

              level_ = input.readInt32();
              break;
            }
            case 56: {

              type_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                params_ = com.google.protobuf.MapField.newMapField(
                    ParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              params__ = input.readMessage(
                  ParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              params_.getMutableMap().put(
                  params__.getKey(), params__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.class, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMID_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomId_;
    /**
     * <code>string roomId = 2;</code>
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      }
    }
    /**
     * <code>string roomId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 3;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object nickname_;
    /**
     * <code>string nickname = 4;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <code>string nickname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private long time_;
    /**
     * <code>int64 time = 5;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <code>int32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>int32 type = 7;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int PARAMS_FIELD_NUMBER = 8;
    private static final class ParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> params_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetParams() {
      if (params_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      return params_;
    }

    public int getParamsCount() {
      return internalGetParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    public boolean containsParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParams() {
      return getParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
      return internalGetParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    public java.lang.String getParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; params = 8;</code>
     */

    public java.lang.String getParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nickname_);
      }
      if (time_ != 0L) {
        output.writeInt64(5, time_);
      }
      if (level_ != 0) {
        output.writeInt32(6, level_);
      }
      if (type_ != 0) {
        output.writeInt32(7, type_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParams(),
          ParamsDefaultEntryHolder.defaultEntry,
          8);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (!getRoomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nickname_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, time_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, type_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        params__ = ParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, params__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage)) {
        return super.equals(obj);
      }
      com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage other = (com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getRoomId()
          .equals(other.getRoomId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && (getTime()
          == other.getTime());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getType()
          == other.getType());
      result = result && internalGetParams().equals(
          other.internalGetParams());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      if (!internalGetParams().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mycompany.im.compute.domain.FromConnectorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mycompany.im.compute.domain.FromConnectorMessage)
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.class, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder.class);
      }

      // Construct using com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";

        roomId_ = "";

        userId_ = "";

        nickname_ = "";

        time_ = 0L;

        level_ = 0;

        type_ = 0;

        internalGetMutableParams().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor;
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getDefaultInstanceForType() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.getDefaultInstance();
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage build() {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage buildPartial() {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage result = new com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageId_ = messageId_;
        result.roomId_ = roomId_;
        result.userId_ = userId_;
        result.nickname_ = nickname_;
        result.time_ = time_;
        result.level_ = level_;
        result.type_ = type_;
        result.params_ = internalGetParams();
        result.params_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage) {
          return mergeFrom((com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage other) {
        if (other == com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getRoomId().isEmpty()) {
          roomId_ = other.roomId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        internalGetMutableParams().mergeFrom(
            other.internalGetParams());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roomId_ = "";
      /**
       * <code>string roomId = 2;</code>
       */
      public java.lang.String getRoomId() {
        java.lang.Object ref = roomId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string roomId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRoomIdBytes() {
        java.lang.Object ref = roomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roomId = 2;</code>
       */
      public Builder setRoomId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roomId = 2;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = getDefaultInstance().getRoomId();
        onChanged();
        return this;
      }
      /**
       * <code>string roomId = 2;</code>
       */
      public Builder setRoomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 3;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 3;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>string nickname = 4;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickname = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickname = 4;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 4;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>string nickname = 4;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 5;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 5;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 5;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 6;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 7;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 7;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 7;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> params_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetParams() {
        if (params_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        return params_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableParams() {
        onChanged();;
        if (params_ == null) {
          params_ = com.google.protobuf.MapField.newMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        if (!params_.isMutable()) {
          params_ = params_.copy();
        }
        return params_;
      }

      public int getParamsCount() {
        return internalGetParams().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public boolean containsParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getParams() {
        return getParamsMap();
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
        return internalGetParams().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public java.lang.String getParamsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public java.lang.String getParamsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParams().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParams() {
        internalGetMutableParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public Builder removeParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableParams() {
        return internalGetMutableParams().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */
      public Builder putParams(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; params = 8;</code>
       */

      public Builder putAllParams(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableParams().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mycompany.im.compute.domain.FromConnectorMessage)
    }

    // @@protoc_insertion_point(class_scope:com.mycompany.im.compute.domain.FromConnectorMessage)
    private static final com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage();
    }

    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FromConnectorMessage>
        PARSER = new com.google.protobuf.AbstractParser<FromConnectorMessage>() {
      public FromConnectorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FromConnectorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FromConnectorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FromConnectorMessage> getParserForType() {
      return PARSER;
    }

    public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FromConnectorMessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mycompany.im.compute.domain.FromConnectorMessages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> 
        getMessagesList();
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getMessages(int index);
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    java.util.List<? extends com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mycompany.im.compute.domain.FromConnectorMessages}
   */
  public  static final class FromConnectorMessages extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mycompany.im.compute.domain.FromConnectorMessages)
      FromConnectorMessagesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FromConnectorMessages.newBuilder() to construct.
    private FromConnectorMessages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FromConnectorMessages() {
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FromConnectorMessages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messages_ = new java.util.ArrayList<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(
                  input.readMessage(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.class, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> messages_;
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    public java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    public java.util.List<? extends com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
     */
    public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages)) {
        return super.equals(obj);
      }
      com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages other = (com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages) obj;

      boolean result = true;
      result = result && getMessagesList()
          .equals(other.getMessagesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mycompany.im.compute.domain.FromConnectorMessages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mycompany.im.compute.domain.FromConnectorMessages)
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.class, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.Builder.class);
      }

      // Construct using com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor;
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages getDefaultInstanceForType() {
        return com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.getDefaultInstance();
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages build() {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages buildPartial() {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages result = new com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages) {
          return mergeFrom((com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages other) {
        if (other == com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messages_ = new java.util.ArrayList<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder addMessages(com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder addMessages(
          com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public java.util.List<? extends com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mycompany.im.compute.domain.FromConnectorMessage messages = 1;</code>
       */
      public java.util.List<com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessage.Builder, com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mycompany.im.compute.domain.FromConnectorMessages)
    }

    // @@protoc_insertion_point(class_scope:com.mycompany.im.compute.domain.FromConnectorMessages)
    private static final com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages();
    }

    public static com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FromConnectorMessages>
        PARSER = new com.google.protobuf.AbstractParser<FromConnectorMessages>() {
      public FromConnectorMessages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FromConnectorMessages(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FromConnectorMessages> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FromConnectorMessages> getParserForType() {
      return PARSER;
    }

    public com.mycompany.im.compute.domain.RoomMsgToCompute.FromConnectorMessages getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RoomMsgToCompute.proto\022\037com.mycompany." +
      "im.compute.domain\"\210\002\n\024FromConnectorMessa" +
      "ge\022\021\n\tmessageId\030\001 \001(\t\022\016\n\006roomId\030\002 \001(\t\022\016\n" +
      "\006userId\030\003 \001(\t\022\020\n\010nickname\030\004 \001(\t\022\014\n\004time\030" +
      "\005 \001(\003\022\r\n\005level\030\006 \001(\005\022\014\n\004type\030\007 \001(\005\022Q\n\006pa" +
      "rams\030\010 \003(\0132A.com.mycompany.im.compute.do" +
      "main.FromConnectorMessage.ParamsEntry\032-\n" +
      "\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"`\n\025FromConnectorMessages\022G\n\010message" +
      "s\030\001 \003(\01325.com.mycompany.im.compute.domai",
      "n.FromConnectorMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor,
        new java.lang.String[] { "MessageId", "RoomId", "UserId", "Nickname", "Time", "Level", "Type", "Params", });
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_descriptor =
      internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_im_compute_domain_FromConnectorMessage_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_im_compute_domain_FromConnectorMessages_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
